- hosts: "{{ env }}"
  become: yes
  tasks: 
    - name: remove any previous app services
      shell: | 
         if [ `kubectl get deploy | grep -v NAME | awk '{print $1}' | grep mynodejsapp | wc -l` -gt 0 ]; then  
            kubectl delete deploy `kubectl get deploy | grep -v NAME | awk '{print $1}' | grep mynodejsapp`
         else 
            echo "No app deployments found"
         fi
         if [ `kubectl get svc | grep mynodejsapp-svc  | awk '{print $1}' | wc -l` -gt 0 ]; then
            kubectl delete svc `kubectl get svc | grep mynodejsapp-svc | awk '{print $1}'`
         else
            echo "No app service found"
         fi
    - name: deploy app
      shell: kubectl create deploy mynodejsapp --image=meetdixit91/mydockerrepo:certProject2_{{ build }}
    - name: increase replicas 
      shell: kubectl scale deploy mynodejsapp --replicas=2
    - name: deploy service
      shell: kubectl expose deploy mynodejsapp --name mynodejsapp-svc --port 8080 --type NodePort
